"""Full PlantVillage DISEASE_DB — all 38 classes.
Keys EXACTLY match disease_classes.json entries.
"""

DISEASE_DB = {
    # ── Apple ──────────────────────────────────────────────────────────────────
    "Apple___Apple_scab": {
        "crop_type": "Apple",
        "disease": "Apple Scab",
        "description": "Fungal disease causing olive-green to brown velvety lesions on leaves and fruits. Infected leaves curl and drop early; fruits develop corky, scabby spots reducing market value.",
        "causes": "Fungus Venturia inaequalis. Spreads via ascospores in spring during wet, cool weather (15–20 °C). Overwintering in fallen leaves.",
        "soil_requirements": "Well-drained loamy soil, pH 6.0–7.0. Avoid waterlogged conditions.",
        "recommended_fertilizers": "Balanced NPK (12-12-12). Supplement potassium to strengthen cell walls. Avoid excess nitrogen which promotes soft, susceptible growth.",
        "pesticide_treatments": "Captan, Mancozeb, or Myclobutanil fungicides. Apply at bud-break and repeat every 7–10 days during wet periods. Neem oil (5 ml/L) as organic option.",
        "soil_moisture": "Maintain 55–65% moisture. Use drip irrigation to keep foliage dry. Never use overhead sprinklers.",
        "preventive_measures": "Remove and destroy fallen leaves. Plant scab-resistant varieties (e.g., Florina). Prune for good air circulation. Apply lime-sulfur sprays during dormancy.",
        "additional_recommendations": "In hilly regions of Himachal Pradesh and Uttarakhand, monitor closely after rain. Early spray calendar (Feb–March) is critical. Store fruits in cool, dry conditions.",
    },
    "Apple___Black_rot": {
        "crop_type": "Apple",
        "disease": "Black Rot",
        "description": "Fungal disease causing 'frog-eye' leaf spots (purple-bordered brown circles), fruit rot (black mummified fruits), and cankers on branches.",
        "causes": "Fungus Botryosphaeria obtusa. Enters through wounds and insect damage. Warm, wet weather (24–28 °C) accelerates spread.",
        "soil_requirements": "Well-drained sandy loam, pH 6.0–7.0. Good drainage essential to reduce root and crown stress.",
        "recommended_fertilizers": "Moderate NPK with emphasis on potassium and calcium to improve fruit skin strength. Avoid excessive nitrogen.",
        "pesticide_treatments": "Captan or Thiophanate-methyl at petal-fall and cover sprays. Remove mummified fruits before applying fungicide.",
        "soil_moisture": "Water deeply but infrequently. Maintain 55–65% field capacity. Avoid wetting the canopy.",
        "preventive_measures": "Prune and destroy dead wood and mummified fruit. Disinfect pruning tools with bleach solution. Control fire blight and insect wounds promptly.",
        "additional_recommendations": "In Kashmiri apple orchards, post-harvest sanitation is the single most effective prevention step. Never leave rotted fruit on the tree or ground.",
    },
    "Apple___Cedar_apple_rust": {
        "crop_type": "Apple",
        "disease": "Cedar Apple Rust",
        "description": "Fungal disease producing bright orange-yellow spots on upper leaf surface with tube-like structures beneath. Causes early defoliation and weakened trees.",
        "causes": "Fungus Gymnosporangium juniperi-virginianae requiring two hosts — apple and cedar/juniper. Spores spread during wet spring weather.",
        "soil_requirements": "Well-drained loam, pH 6.0–7.0.",
        "recommended_fertilizers": "Balanced NPK. Increase potassium during fruiting season to improve disease resistance.",
        "pesticide_treatments": "Myclobutanil, Propiconazole, or Mancozeb from pink bud stage through petal-fall. Repeat every 7–10 days during wet weather.",
        "soil_moisture": "Moderate and consistent. Avoid overhead irrigation during flowering and early fruit set.",
        "preventive_measures": "Remove nearby juniper/cedar trees if possible. Plant rust-resistant apple varieties. Apply protective fungicide sprays in spring.",
        "additional_recommendations": "Rare in most Indian growing zones but relevant in high-altitude Himalayan orchards near juniper-dense forests. Monitor orchards bordering forest areas.",
    },
    "Apple___healthy": {
        "crop_type": "Apple",
        "disease": "Healthy (No Disease Detected)",
        "description": "The apple tree appears healthy with no visible signs of disease. Continue regular monitoring and preventive care.",
        "causes": "N/A",
        "soil_requirements": "Well-drained loamy soil, pH 6.0–7.0. Rich in organic matter.",
        "recommended_fertilizers": "NPK 70:35:70 g/tree/year. Apply well-rotted FYM (25 kg/tree) before bud-break. Foliar zinc spray improves fruit quality.",
        "pesticide_treatments": "Apply preventive neem oil spray (5 ml/L) monthly. Bordeaux mixture spray during dormancy.",
        "soil_moisture": "60–70% field capacity. Deep watering every 10–14 days in dry periods. Mulch with straw to retain moisture.",
        "preventive_measures": "Regular pruning in winter, annual canopy thinning, remove dead wood, monitor for early pest and disease signs.",
        "additional_recommendations": "In Himachal Pradesh, apply borax spray during pre-bloom to prevent cork spot. Thin fruits to one per cluster for larger, premium apples.",
    },

    # ── Blueberry ──────────────────────────────────────────────────────────────
    "Blueberry___healthy": {
        "crop_type": "Blueberry",
        "disease": "Healthy (No Disease Detected)",
        "description": "Blueberry plant is healthy. Maintain acidic soil conditions and good cultural practices for continued health.",
        "causes": "N/A",
        "soil_requirements": "Acidic, well-drained sandy loam, pH 4.5–5.5. Rich in organic matter. Add sulfur to lower pH if needed.",
        "recommended_fertilizers": "Ammonium sulfate (acidifying fertilizer). Avoid chloride-based fertilizers. Apply in split doses — March and June.",
        "pesticide_treatments": "Preventive copper-based spray before bud-break. Neem oil for aphid control.",
        "soil_moisture": "Consistent moisture at 60–70%. Blueberries have shallow roots — mulch heavily (10 cm pine bark) to retain moisture.",
        "preventive_measures": "Net against birds, prune old canes, maintain weed-free zone around plant base.",
        "additional_recommendations": "Grown commercially in Nilgiris and Himachal Pradesh. Ensure full-sun location. Blueberries need 800–1000 chill hours — suited to cooler hill stations.",
    },

    # ── Cherry ─────────────────────────────────────────────────────────────────
    "Cherry_(including_sour)___Powdery_mildew": {
        "crop_type": "Cherry",
        "disease": "Powdery Mildew",
        "description": "White powdery fungal coating on young leaves, shoots, and fruit surface. Infected leaves curl upward, shoots become distorted, and fruit quality declines.",
        "causes": "Fungus Podosphaera clandestina. Thrives in warm days (20–27 °C) with cool nights and high humidity. Does NOT require wet leaves — dry weather with high RH favors it.",
        "soil_requirements": "Well-drained loam, pH 6.5–7.0. Avoid excessive nitrogen which promotes soft vegetative growth.",
        "recommended_fertilizers": "Balanced NPK with reduced nitrogen in summer. Potassium silicate sprays improve leaf resistance.",
        "pesticide_treatments": "Sulphur-based fungicides (wettable sulphur 2 g/L), Hexaconazole, or Trifloxystrobin. Apply at first sign and every 10–14 days.",
        "soil_moisture": "Moderate irrigation. Avoid over-watering which promotes lush, susceptible shoots.",
        "preventive_measures": "Prune to open canopy. Remove infected shoots immediately. Plant resistant varieties. Avoid late-season nitrogen fertilization.",
        "additional_recommendations": "Common in Jammu & Kashmir cherry orchards during dry summers. Early morning sulphur dust application is effective and economical for small farmers.",
    },
    "Cherry_(including_sour)___healthy": {
        "crop_type": "Cherry",
        "disease": "Healthy (No Disease Detected)",
        "description": "Cherry tree is healthy. Continue standard orchard management for optimum fruit yield.",
        "causes": "N/A",
        "soil_requirements": "Deep, well-drained loamy soil, pH 6.5–7.0. Avoid heavy clay soils.",
        "recommended_fertilizers": "100 g N, 50 g P, 100 g K per tree per year. Apply FYM 20–30 kg/tree annually. Foliar boron spray at balloon-bud stage improves fruit set.",
        "pesticide_treatments": "Bordeaux mixture (1%) spray during dormancy. Chlorpyrifos for borer control if needed.",
        "soil_moisture": "Regular irrigation especially during fruit development. Avoid water stress at stone-hardening stage which causes split pits.",
        "preventive_measures": "Annual winter pruning, remove water sprouts, white-wash trunk to prevent sunscald and borer entry.",
        "additional_recommendations": "In J&K and Himachal Pradesh, timely thinning of overcrowded orchards improves fruit size. Net against birds during harvest.",
    },

    # ── Corn (maize) ───────────────────────────────────────────────────────────
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "crop_type": "Corn (Maize)",
        "disease": "Gray Leaf Spot (Cercospora)",
        "description": "Rectangular, tan-to-gray lesions with distinct parallel edges (following leaf veins) on lower leaves. Severe infection causes premature leaf death and significant yield loss.",
        "causes": "Fungus Cercospora zeae-maydis. Favored by warm (25–30 °C), humid weather with extended leaf wetness. Spreads via air and infected crop debris.",
        "soil_requirements": "Well-drained fertile loam, pH 6.0–7.0. Avoid compacted soils that stress plants.",
        "recommended_fertilizers": "Full NPK as per soil test. Adequate nitrogen (120 kg/ha) and zinc (25 kg ZnSO4/ha) reduce plant stress and susceptibility.",
        "pesticide_treatments": "Azoxystrobin, Propiconazole, or Mancozeb. Apply at early tassel stage and repeat if disease pressure is high.",
        "soil_moisture": "Maintain consistent moisture — 50–60% field capacity. Avoid overhead irrigation at night.",
        "preventive_measures": "Plant resistant hybrids. Practice crop rotation (avoid maize-maize). Deep plow to bury infected debris. Sow at recommended density to allow airflow.",
        "additional_recommendations": "Common in humid zones of Maharashtra, Karnataka, and MP during kharif season. Reduce plant density in high-disease-pressure fields.",
    },
    "Corn_(maize)___Common_rust_": {
        "crop_type": "Corn (Maize)",
        "disease": "Common Rust",
        "description": "Small, circular to elongated brick-red powdery pustules on both leaf surfaces. Heavily infected leaves turn yellow and dry up, reducing photosynthesis and yield.",
        "causes": "Fungus Puccinia sorghi. Spreads rapidly by wind-blown urediniospores. Favored by cool temperatures (16–23 °C) and high humidity.",
        "soil_requirements": "Well-drained loam, pH 6.0–7.0. Ensure adequate soil potassium levels.",
        "recommended_fertilizers": "Potassium-rich fertilizers (MOP 60 kg/ha) to improve plant immunity. Balanced NPK per crop requirement.",
        "pesticide_treatments": "Mancozeb (2 g/L) or Propiconazole (1 ml/L). Spray at first appearance of pustules and repeat after 10 days.",
        "soil_moisture": "Moderate — 50–65% field capacity. Avoid irrigation during cool nights which prolong leaf wetness.",
        "preventive_measures": "Grow rust-resistant hybrid varieties. Early sowing to avoid peak disease period. Destroy volunteer maize plants which harbor the fungus.",
        "additional_recommendations": "Common in hilly maize-growing areas of North India during September–October. Monitor weekly from V6 stage onward.",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "crop_type": "Corn (Maize)",
        "disease": "Northern Leaf Blight",
        "description": "Long (5–15 cm), cigar-shaped, grayish-green to tan lesions on leaves. Infected fields look scorched. Can cause 30–50% yield loss in severe cases.",
        "causes": "Fungus Exserohilum turcicum. Spreads by wind and rain splash from infected debris. Favored by moderate temperatures (18–27 °C) and high humidity.",
        "soil_requirements": "Well-drained fertile soil, pH 5.8–7.0.",
        "recommended_fertilizers": "Full NPK (120:60:60 kg/ha). Adequate silicon and potassium improve resistance.",
        "pesticide_treatments": "Mancozeb (2.5 g/L) or Azoxystrobin + Propiconazole (1 ml/L). Apply at V8 stage before tasseling for best results.",
        "soil_moisture": "Moderate, consistent irrigation. Reduce overhead watering. Allow fields to dry between irrigations.",
        "preventive_measures": "Plant resistant/tolerant hybrids. Crop rotation with non-host crops (soybean, wheat). Deep tillage to bury infected residue.",
        "additional_recommendations": "Critical during kharif season in Rajasthan, MP, and UP. Combining resistant varieties with timely fungicide is the most cost-effective strategy.",
    },
    "Corn_(maize)___healthy": {
        "crop_type": "Corn (Maize)",
        "disease": "Healthy (No Disease Detected)",
        "description": "Maize crop appears healthy and vigorous. Maintain recommended agronomic practices for maximum yield.",
        "causes": "N/A",
        "soil_requirements": "Deep, well-drained loamy soil, pH 6.0–7.5. High organic matter content improves nutrient availability.",
        "recommended_fertilizers": "120:60:60 kg NPK/ha. Apply 1/3 N + full P + full K at sowing; 1/3 N at knee-high stage; 1/3 N at tasseling. Zinc sulfate 25 kg/ha at sowing.",
        "pesticide_treatments": "Seed treatment with Thiram + Carbendazim before sowing. Monitor for fall armyworm (Spodoptera frugiperda) regularly.",
        "soil_moisture": "Critical stages: knee-high, tasseling, and grain-fill. Maintain 60–70% field capacity at these stages. Avoid water stress.",
        "preventive_measures": "Weed-free in first 30 days. Optimal plant population (60,000–65,000 plants/ha). Timely sowing in June for kharif crop.",
        "additional_recommendations": "Spray Emamectin benzoate (0.4 g/L) for fall armyworm control — most damaging pest in current Indian maize scenario. Keep field records for rotation planning.",
    },

    # ── Grape ──────────────────────────────────────────────────────────────────
    "Grape___Black_rot": {
        "crop_type": "Grape",
        "disease": "Black Rot",
        "description": "Starts as small tan leaf spots with dark margins. Fruits develop brown rot and shrivel into hard black mummies. Can destroy entire grape clusters.",
        "causes": "Fungus Guignardia bidwellii. Requires wet weather and 10+ hours leaf wetness at 21–29 °C. Overwinters in mummified berries and infected canes.",
        "soil_requirements": "Well-drained, deep loam or sandy loam, pH 6.0–6.5.",
        "recommended_fertilizers": "Moderate NPK. Potassium is critical for berry development and disease resistance. Avoid excess nitrogen.",
        "pesticide_treatments": "Mancozeb or Captan from bud-break through post-bloom. Myclobutanil for curative action. Spray schedule every 7–10 days during wet weather.",
        "soil_moisture": "Drip irrigation only. Keep canopy dry. Avoid any overhead watering system in vineyards.",
        "preventive_measures": "Remove and destroy mummified berries and infected canes during pruning. Maintain open canopy. Apply dormant copper spray.",
        "additional_recommendations": "Damaging in Nashik and Sangli wine grape regions during pre-monsoon humid periods. Strict spray calendar from February to June is essential.",
    },
    "Grape___Esca_(Black_Measles)": {
        "crop_type": "Grape",
        "disease": "Esca (Black Measles)",
        "description": "Complex fungal wood disease causing tiger-stripe leaf patterns (interveinal chlorosis/necrosis), shriveled berries with dark spots, and sudden vine collapse (apoplexy).",
        "causes": "Complex of wood-decaying fungi (Phaeomoniella chlamydospora, Phaeoacremonium spp.). Enters through pruning wounds. Stress from drought or extreme temperatures triggers apoplexy.",
        "soil_requirements": "Well-drained deep soil, pH 6.0–7.0. Avoid heavy soils causing root stress.",
        "recommended_fertilizers": "Balanced nutrition with emphasis on magnesium and potassium. Foliar sprays of micronutrients support stressed vines.",
        "pesticide_treatments": "No fully curative chemical treatment. Apply wound sealant paste (Trichoderma-based) immediately after pruning. Sodium arsenite is banned in India.",
        "soil_moisture": "Avoid water stress — critical for preventing apoplexy. Consistent drip irrigation throughout growing season.",
        "preventive_measures": "Make clean pruning cuts during dry weather. Seal all wounds with fungicidal paste. Remove and burn severely infected vines.",
        "additional_recommendations": "Rare but emerging in old Indian vineyards (>10 years). Replanting with certified disease-free rootstocks is the long-term solution.",
    },
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
        "crop_type": "Grape",
        "disease": "Leaf Blight (Isariopsis Leaf Spot)",
        "description": "Irregular dark brown to black spots on leaves with a yellowish halo. Severely infected leaves dry up and fall early, weakening vine and reducing fruit quality.",
        "causes": "Fungus Pseudocercospora vitis (formerly Isariopsis clavispora). Favored by warm, humid conditions and prolonged wet weather.",
        "soil_requirements": "Well-drained loamy soil, pH 6.0–7.0.",
        "recommended_fertilizers": "Balanced NPK; potassium-rich fertilizer to improve vine immunity.",
        "pesticide_treatments": "Copper oxychloride (3 g/L), Mancozeb (2 g/L), or Carbendazim (1 g/L). Spray at first sign and repeat every 10–14 days.",
        "soil_moisture": "Moderate, consistent drip irrigation. Avoid wetting foliage.",
        "preventive_measures": "Remove infected leaves promptly. Improve air circulation by shoot positioning and leaf removal. Avoid dense canopy.",
        "additional_recommendations": "Common in Andhra Pradesh and Karnataka table grape vineyards during humid months. Copper-based sprays are economical and effective.",
    },
    "Grape___healthy": {
        "crop_type": "Grape",
        "disease": "Healthy (No Disease Detected)",
        "description": "Grapevine is healthy. Follow the recommended pruning, irrigation, and spray schedule to maintain productivity.",
        "causes": "N/A",
        "soil_requirements": "Well-drained, deep loamy soil, pH 6.5–7.5. Grapes tolerate a range of soils but not waterlogged conditions.",
        "recommended_fertilizers": "NPK 50:50:75 kg/ha at pruning. FYM 20–25 kg/vine annually. Magnesium sulfate foliar spray for fruit quality.",
        "pesticide_treatments": "Preventive Bordeaux mixture (1%) at pruning and bud-break. Mancozeb spray before and after monsoon.",
        "soil_moisture": "Drip irrigation — 8–10 L/vine/day in summer, less in winter. Mulch to conserve moisture and suppress weeds.",
        "preventive_measures": "Systematic dormancy pruning, shoot positioning, canopy management, and regular 3-spray cycle (pre-monsoon, monsoon, post-monsoon).",
        "additional_recommendations": "In Nashik and Sangli, follow the agro-advisory from NRCG (National Research Centre for Grapes) for seasonal spray calendar. Timely harvesting prevents botrytis bunch rot.",
    },

    # ── Orange ─────────────────────────────────────────────────────────────────
    "Orange___Haunglongbing_(Citrus_greening)": {
        "crop_type": "Orange",
        "disease": "Huanglongbing / Citrus Greening",
        "description": "Most destructive citrus disease globally. Causes asymmetric leaf yellowing (blotchy mottle), stunted shoots, small lopsided bitter fruits, and eventual tree death within years.",
        "causes": "Bacterium Candidatus Liberibacter asiaticus, spread by Asian citrus psyllid (Diaphorina citri). No cure once infected.",
        "soil_requirements": "Well-drained loam, pH 6.0–7.0. Healthy soil reduces tree stress and slows disease progression.",
        "recommended_fertilizers": "Intensified micronutrient feeding — foliar zinc, manganese, boron, and iron to prolong productivity of infected trees.",
        "pesticide_treatments": "Control vector: Imidacloprid soil drench or Dimethoate spray for psyllid control. No antibiotic treatment is approved or effective long-term.",
        "soil_moisture": "Regular, consistent irrigation reduces tree stress and may slow symptom progression.",
        "preventive_measures": "Use certified disease-free nursery plants. Control psyllid population aggressively. Remove and destroy infected trees immediately to prevent spread.",
        "additional_recommendations": "Devastating in citrus belts of Vidarbha (Maharashtra), Coorg (Karnataka), and Assam. Report suspected cases to local horticulture department. Replant with disease-free budded plants on tolerant rootstocks.",
    },

    # ── Peach ──────────────────────────────────────────────────────────────────
    "Peach___Bacterial_spot": {
        "crop_type": "Peach",
        "disease": "Bacterial Spot",
        "description": "Water-soaked spots on leaves that turn brown-purple with a yellow halo; leaves fall prematurely. Fruit develops sunken, cracked spots reducing marketability significantly.",
        "causes": "Bacterium Xanthomonas arboricola pv. pruni. Spreads via rain splash and wind. Favored by warm (24–28 °C), rainy, and windy conditions.",
        "soil_requirements": "Well-drained sandy loam, pH 6.0–6.8. Avoid heavy soils that stay wet.",
        "recommended_fertilizers": "Moderate nitrogen; high potassium and calcium to improve fruit skin toughness and resistance.",
        "pesticide_treatments": "Copper hydroxide or Copper oxychloride (3 g/L). Apply from shuck-split through harvest at 7–10 day intervals during wet weather. Oxytetracycline may be used pre-harvest.",
        "soil_moisture": "Consistent drip irrigation. Avoid overhead watering which spreads the bacterium.",
        "preventive_measures": "Plant resistant varieties. Avoid pruning during wet weather. Remove infected shoots and mummified fruits.",
        "additional_recommendations": "Common in J&K and Himachal Pradesh hill peach orchards during rainy season. Windbreaks help reduce bacterial spread in exposed orchards.",
    },
    "Peach___healthy": {
        "crop_type": "Peach",
        "disease": "Healthy (No Disease Detected)",
        "description": "Peach tree is healthy. Maintain standard orchard practices for a productive crop.",
        "causes": "N/A",
        "soil_requirements": "Deep, well-drained sandy loam, pH 6.0–7.0. Good drainage is critical — peaches are sensitive to waterlogging.",
        "recommended_fertilizers": "100–150 g N, 60 g P2O5, 80 g K2O per tree per year in split doses. FYM 20 kg/tree at planting and annually. Foliar zinc and boron improve fruit quality.",
        "pesticide_treatments": "Dormant copper spray, carbaryl for fruit thinning where needed, and insecticide spray for peach fruit borer.",
        "soil_moisture": "Critical at petal-fall and fruit-fill stages. Maintain 65% field capacity. Mulch with paddy straw to conserve moisture.",
        "preventive_measures": "Annual pruning, thinning fruits to 15–20 cm spacing, remove water sprouts, and apply white-wash to trunk.",
        "additional_recommendations": "Harvest when fruit has full-colour development. Peaches are highly perishable — pre-cool at 0–2 °C immediately after harvest. Market promptly.",
    },

    # ── Pepper ─────────────────────────────────────────────────────────────────
    "Pepper,_bell___Bacterial_spot": {
        "crop_type": "Bell Pepper",
        "disease": "Bacterial Spot",
        "description": "Water-soaked spots on leaves turn dark brown with yellow halos; fruit develops raised, scabby lesions reducing quality and marketability.",
        "causes": "Bacterium Xanthomonas campestris pv. vesicatoria. Spread by rain splash and infected seed. Favored by warm, wet weather (24–30 °C).",
        "soil_requirements": "Well-drained sandy loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Moderate NPK with calcium and potassium emphasis. Excess nitrogen worsens severity.",
        "pesticide_treatments": "Copper hydroxide (3 g/L) or Copper oxychloride sprays every 7–10 days during wet weather. Streptomycin sulfate (100 ppm) for severe outbreaks.",
        "soil_moisture": "Drip irrigation only. Avoid wetting foliage. Maintain 60–65% field capacity.",
        "preventive_measures": "Use certified disease-free seed. Hot-water seed treatment (52 °C, 30 min). Rotate crops — avoid solanaceous crops for 2–3 years.",
        "additional_recommendations": "Common in capsicum-growing belts of Himachal Pradesh and Karnataka during monsoon. Copper sprays immediately after heavy rain are critical.",
    },
    "Pepper,_bell___healthy": {
        "crop_type": "Bell Pepper",
        "disease": "Healthy (No Disease Detected)",
        "description": "Bell pepper plant is healthy. Continue standard crop management for good yield.",
        "causes": "N/A",
        "soil_requirements": "Well-drained sandy loam rich in organic matter, pH 6.0–7.0.",
        "recommended_fertilizers": "NPK 120:60:80 kg/ha. Apply boron (1 g/L foliar) at flowering for better fruit set. FYM 20 t/ha at land preparation.",
        "pesticide_treatments": "Preventive neem oil spray (5 ml/L) fortnightly. Imidacloprid for thrips and aphid control.",
        "soil_moisture": "Consistent drip irrigation. Critical stages: transplanting, flowering, and fruit set. Avoid waterlogging.",
        "preventive_measures": "Stake plants for support, mulch with plastic or straw, and scout weekly for pests.",
        "additional_recommendations": "Shade nets reduce sunscald during peak summer in South India. Harvest at full-green stage for better shelf life.",
    },

    # ── Potato ─────────────────────────────────────────────────────────────────
    "Potato___Early_blight": {
        "crop_type": "Potato",
        "disease": "Early Blight",
        "description": "Dark brown, target-like concentric ring spots on older leaves. Infected leaves yellow and die, reducing tuber size and yield by 20–30%.",
        "causes": "Fungus Alternaria solani. Favored by warm days (24–29 °C), cool nights, and alternating dry/wet conditions. Overwinters in infected debris and tubers.",
        "soil_requirements": "Well-drained sandy loam, pH 5.0–6.5.",
        "recommended_fertilizers": "Balanced NPK 180:80:100 kg/ha. Adequate nitrogen is essential — nitrogen-deficient plants are most susceptible.",
        "pesticide_treatments": "Mancozeb (2.5 g/L) or Chlorothalonil every 7–10 days. Start preventive sprays 30–35 days after planting.",
        "soil_moisture": "60–65% field capacity. Furrow or drip irrigation preferred. Avoid excessive moisture that stresses plants.",
        "preventive_measures": "Use certified disease-free seed tubers. Crop rotation with non-solanaceous crops. Remove crop debris after harvest.",
        "additional_recommendations": "Highly common in UP, Bihar, and West Bengal potato belts. Preventive spray calendar starting before disease appearance is more effective than curative sprays.",
    },
    "Potato___Late_blight": {
        "crop_type": "Potato",
        "disease": "Late Blight",
        "description": "Water-soaked, gray-green lesions with white mold on leaf undersides; spreads rapidly in wet weather and can destroy an entire field within days.",
        "causes": "Oomycete Phytophthora infestans. Spreads explosively by wind-blown sporangia during cool (10–20 °C), wet, foggy conditions.",
        "soil_requirements": "Well-drained loamy soil, pH 5.0–6.5. Good drainage slows soil-borne spread to tubers.",
        "recommended_fertilizers": "Balanced NPK. Potassium strengthens cell walls and reduces infection rate. Avoid excess nitrogen.",
        "pesticide_treatments": "Metalaxyl + Mancozeb (2 g/L), Cymoxanil + Mancozeb, or Dimethomorph for resistant strains. Spray every 5–7 days during epidemic risk.",
        "soil_moisture": "Avoid over-irrigation. Never irrigate in the evening. Raise beds for good drainage.",
        "preventive_measures": "Plant resistant varieties (Kufri Khyati, Kufri Girdhari). Use disease-free seed. Earth up to protect tubers from sporangia wash-down.",
        "additional_recommendations": "Most feared disease in Shimla hills and UP plains during foggy winters. Subscribe to NIPHM blight forecasting alerts. Act within 24 hours of warning.",
    },
    "Potato___healthy": {
        "crop_type": "Potato",
        "disease": "Healthy (No Disease Detected)",
        "description": "Potato crop is healthy and growing well. Maintain standard agronomy for optimum tuber yield.",
        "causes": "N/A",
        "soil_requirements": "Deep, loose, well-drained sandy loam, pH 5.2–6.4. Friable soil ensures good tuber development.",
        "recommended_fertilizers": "NPK 180:80:100 kg/ha. Apply full P and K at planting; split N at planting and earthing-up. Zinc sulfate 25 kg/ha improves quality.",
        "pesticide_treatments": "Seed-treatment with Mancozeb (3 g/kg) before planting. Scout for aphids (virus vectors) weekly.",
        "soil_moisture": "Critical at tuber initiation (45–55 DAP). Maintain 65–70% field capacity. Stop irrigation 2 weeks before harvest for skin-set.",
        "preventive_measures": "Use certified seed, practice 3-year crop rotation, earthing-up at 30–35 DAP, timely vine killing before harvest.",
        "additional_recommendations": "For seed potato crop, rogue out virus-infected plants early. In cold stores, maintain 2–4 °C and 90–95% RH for 6-month storage.",
    },

    # ── Raspberry, Soybean, Squash ─────────────────────────────────────────────
    "Raspberry___healthy": {
        "crop_type": "Raspberry",
        "disease": "Healthy (No Disease Detected)",
        "description": "Raspberry canes are healthy. Follow biennial cane management and regular pest monitoring.",
        "causes": "N/A",
        "soil_requirements": "Well-drained, fertile loam, pH 5.6–6.2. High organic matter content is essential.",
        "recommended_fertilizers": "NPK 80:40:80 kg/ha per year. FYM 20 t/ha. Topdress with ammonium nitrate in early spring.",
        "pesticide_treatments": "Preventive lime-sulfur spray during dormancy. Captan for botrytis control at flowering.",
        "soil_moisture": "Consistent moisture — 65–70% field capacity. Mulch thickly to conserve moisture and suppress weeds.",
        "preventive_measures": "Remove and burn floricanes after harvest. Thin primocanes to 6 per meter. Control aphids to prevent virus spread.",
        "additional_recommendations": "Grown in Himachal Pradesh and Uttarakhand hill areas. Trellis canes properly to improve light penetration and air circulation.",
    },
    "Soybean___healthy": {
        "crop_type": "Soybean",
        "disease": "Healthy (No Disease Detected)",
        "description": "Soybean crop is healthy. Maintain inoculation and recommended nutrient management for optimum nitrogen fixation and yield.",
        "causes": "N/A",
        "soil_requirements": "Well-drained loam, pH 6.0–7.0. Adequate phosphorus and molybdenum for nodulation.",
        "recommended_fertilizers": "Starter NPK 20:60:40 kg/ha. Seed inoculation with Bradyrhizobium japonicum is critical. Zinc sulfate 25 kg/ha where deficient.",
        "pesticide_treatments": "Imidacloprid seed treatment for sucking pests. Monitor for semilooper and pod borer during reproductive stages.",
        "soil_moisture": "Critical at flowering and pod-fill stages. Maintain 60–70% field capacity. Soybean is sensitive to both drought and waterlogging.",
        "preventive_measures": "Timely sowing (June 20–July 10 in Central India), recommended seed rate, weed control in first 30 days.",
        "additional_recommendations": "MP, Maharashtra, and Rajasthan are major soybean states. Avoid late sowing — each week's delay beyond July 15 reduces yield by 5–8%.",
    },
    "Squash___Powdery_mildew": {
        "crop_type": "Squash",
        "disease": "Powdery Mildew",
        "description": "White, powdery fungal colonies on upper and lower leaf surfaces. Infected leaves yellow and die prematurely, reducing fruit set and quality.",
        "causes": "Fungi Podosphaera xanthii and Erysiphe cichoracearum. Thrives in warm, dry conditions with high humidity — does not require leaf wetness.",
        "soil_requirements": "Well-drained sandy loam, pH 6.0–7.0.",
        "recommended_fertilizers": "Balanced NPK; potassium silicate sprays (1%) improve leaf resistance to powdery mildew.",
        "pesticide_treatments": "Wettable sulphur (2.5 g/L), Hexaconazole (1 ml/L), or Myclobutanil at first sign. Spray every 10–12 days.",
        "soil_moisture": "Moderate and consistent. Overhead watering actually reduces powdery mildew — but avoid excessive moisture that causes other diseases.",
        "preventive_measures": "Plant resistant varieties. Ensure proper plant spacing (1.5–2 m) for airflow. Remove infected leaves promptly.",
        "additional_recommendations": "Common across all cucurbit-growing regions of India during dry months (Oct–Feb). Sulphur dust in the morning is an economical preventive measure.",
    },

    # ── Strawberry ─────────────────────────────────────────────────────────────
    "Strawberry___Leaf_scorch": {
        "crop_type": "Strawberry",
        "disease": "Leaf Scorch",
        "description": "Small, irregular purple to dark-brown spots on leaf surface that coalesce; leaves turn reddish-brown and appear scorched. Severely reduces plant vigor.",
        "causes": "Fungus Diplocarpon earlianum. Spread by rain splash during cool, wet weather. Overwinters in infected leaves.",
        "soil_requirements": "Well-drained, slightly acidic sandy loam, pH 5.5–6.5.",
        "recommended_fertilizers": "NPK 100:60:80 kg/ha. Avoid excess nitrogen. Potassium improves disease resistance.",
        "pesticide_treatments": "Captan (2 g/L) or Myclobutanil (1 ml/L) at 10–14 day intervals during wet weather.",
        "soil_moisture": "Drip irrigation only. Avoid wetting foliage. Mulch with black plastic to prevent soil-splash.",
        "preventive_measures": "Remove old infected leaves before monsoon. Plant certified disease-free runners. Maintain plant spacing of 30×30 cm.",
        "additional_recommendations": "Common in Mahabaleshwar, Ooty, and Himachal Pradesh strawberry farms. Plastic mulch + drip irrigation significantly reduces disease incidence.",
    },
    "Strawberry___healthy": {
        "crop_type": "Strawberry",
        "disease": "Healthy (No Disease Detected)",
        "description": "Strawberry plant is healthy with no visible disease symptoms. Maintain good bed management and runner control.",
        "causes": "N/A",
        "soil_requirements": "Slightly acidic, well-drained sandy loam, pH 5.5–6.5, rich in organic matter.",
        "recommended_fertilizers": "NPK 100:60:80 kg/ha. Fertigation through drip: split doses of N and K every 15 days during growing season. Boron foliar spray improves fruit quality.",
        "pesticide_treatments": "Preventive Captan spray monthly. Abamectin for two-spotted spider mite control. Spinosad for thrips.",
        "soil_moisture": "Consistent drip irrigation — 2–4 L/plant/day. Plastic mulch conserves moisture and keeps fruits clean.",
        "preventive_measures": "Use certified disease-free runners, replace plants every 2–3 years, control runners to maintain plant vigor.",
        "additional_recommendations": "In Mahabaleshwar, plant September–October for February–April harvest. Refrigerated transport (0–2 °C) is essential for export-quality fruit.",
    },

    # ── Tomato ─────────────────────────────────────────────────────────────────
    "Tomato___Bacterial_spot": {
        "crop_type": "Tomato",
        "disease": "Bacterial Spot",
        "description": "Small, water-soaked spots on leaves with yellow halos turn dark brown; fruit develops raised, scabby lesions reducing marketability.",
        "causes": "Xanthomonas vesicatoria. Spreads by rain splash and contaminated seed. Warm, wet weather (24–30 °C) accelerates spread.",
        "soil_requirements": "Well-drained loam, pH 6.0–7.0.",
        "recommended_fertilizers": "Moderate NPK with emphasis on calcium and potassium to strengthen plant tissue.",
        "pesticide_treatments": "Copper oxychloride (3 g/L) every 7–10 days. Streptomycin (100 ppm) for severe outbreaks. Avoid applications during high heat.",
        "soil_moisture": "Drip irrigation. Avoid overhead watering which spreads bacteria. Maintain 60–65% field capacity.",
        "preventive_measures": "Use certified seed; hot-water treatment (52 °C, 30 min); 2–3 year rotation away from solanaceous crops.",
        "additional_recommendations": "Prevalent in Karnataka, Maharashtra, and AP tomato belts during monsoon. Remove heavily infected leaves immediately.",
    },
    "Tomato___Early_blight": {
        "crop_type": "Tomato",
        "disease": "Early Blight",
        "description": "Target-like dark brown concentric ring spots on older lower leaves; infected leaves yellow and drop, exposing fruit to sunscald.",
        "causes": "Fungus Alternaria solani. Favored by alternating wet and dry conditions at 24–29 °C. Overwinters in infected crop debris.",
        "soil_requirements": "Well-drained loamy soil, pH 6.0–6.8.",
        "recommended_fertilizers": "Full NPK (150:75:75 kg/ha). Nitrogen-deficient plants are most susceptible; maintain adequate nutrition.",
        "pesticide_treatments": "Mancozeb (2.5 g/L) or Chlorothalonil (2 g/L) sprays every 7 days. Azoxystrobin for systemic control in severe cases.",
        "soil_moisture": "Consistent drip irrigation. Avoid water stress which predisposes plants to infection. Mulch to prevent soil splash.",
        "preventive_measures": "Use resistant varieties, remove lower infected leaves, practice 2-year crop rotation, destroy crop debris after harvest.",
        "additional_recommendations": "One of the most common tomato diseases across India. Start spray program 30 days after transplanting before disease appears.",
    },
    "Tomato___Late_blight": {
        "crop_type": "Tomato",
        "disease": "Late Blight",
        "description": "Irregular gray-green water-soaked patches on leaves with white mold on undersides; fruits develop brown firm rot. Can collapse a crop within a week in cool, wet weather.",
        "causes": "Oomycete Phytophthora infestans. Spreads explosively by wind-blown sporangia at 10–20 °C with high humidity.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8. Good drainage prevents soilborne fruit rot.",
        "recommended_fertilizers": "Potassium-rich fertilizers (100 kg K2O/ha) improve resistance. Balanced nutrition reduces plant stress.",
        "pesticide_treatments": "Metalaxyl + Mancozeb (2 g/L) or Cymoxanil + Mancozeb. Spray every 5–7 days during epidemic conditions. Rotate fungicides to prevent resistance.",
        "soil_moisture": "Drip only. Avoid evening irrigation. Raised beds improve drainage.",
        "preventive_measures": "Plant resistant varieties, avoid dense planting, stake plants for airflow, remove infected plants immediately.",
        "additional_recommendations": "Critical threat in Ooty, Himachal Pradesh, and hilly areas during rainy seasons. Monitor disease forecasting services and act proactively.",
    },
    "Tomato___Leaf_Mold": {
        "crop_type": "Tomato",
        "disease": "Leaf Mold",
        "description": "Pale yellowish spots on upper leaf surface with olive-green to grayish-purple velvety mold on lower surface. Primarily a greenhouse problem in India.",
        "causes": "Fungus Passalora fulva (formerly Fulvia fulva). Thrives in high humidity (>85%) and moderate temperatures (22–25 °C). Spreads by airborne conidia.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Balanced NPK. Avoid excess nitrogen which promotes lush, susceptible foliage.",
        "pesticide_treatments": "Chlorothalonil (2 g/L), Mancozeb, or Copper hydroxide. Azoxystrobin for systemic control. Spray lower leaf surfaces thoroughly.",
        "soil_moisture": "Drip irrigation. Reduce humidity in poly-houses by ventilation. Target 70–75% RH.",
        "preventive_measures": "Ensure adequate ventilation in greenhouse. Remove infected leaves. Plant resistant hybrid varieties. Avoid overcrowding.",
        "additional_recommendations": "Increasing problem in Maharashtra and AP protected cultivation. Install proper ridge vents and side nets in poly-houses for humidity management.",
    },
    "Tomato___Septoria_leaf_spot": {
        "crop_type": "Tomato",
        "disease": "Septoria Leaf Spot",
        "description": "Numerous small, circular spots (3–6 mm) with dark borders and white-gray centers on lower leaves. Causes severe defoliation from the bottom upward.",
        "causes": "Fungus Septoria lycopersici. Spreads by rain splash and working in wet fields. Favored by warm (20–25 °C), wet conditions.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Balanced NPK; avoid nitrogen excess. Adequate potassium improves resistance.",
        "pesticide_treatments": "Mancozeb (2.5 g/L), Chlorothalonil (2 g/L), or Copper oxychloride every 7–10 days from first appearance.",
        "soil_moisture": "Drip irrigation only. Mulch to prevent soil splash onto lower leaves.",
        "preventive_measures": "Avoid working in wet fields, stake plants, remove lower leaves when first symptoms appear, 2-year crop rotation.",
        "additional_recommendations": "Often confused with early blight — septoria spots are smaller with lighter centers. Proper ID helps select the right fungicide.",
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "crop_type": "Tomato",
        "disease": "Spider Mites (Two-Spotted)",
        "description": "Tiny mites cause stippling (tiny white/yellow dots) on leaf surface; severe infestation leads to bronzing, webbing, and leaf drop. Not a fungal disease — requires miticide.",
        "causes": "Arachnid Tetranychus urticae. Thrives in hot, dry conditions (28–35 °C, low humidity). Populations explode during drought stress.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8. Soil health indirectly affects plant vigor and mite resistance.",
        "recommended_fertilizers": "Balanced NPK; adequate silicon (potassium silicate foliar) reduces mite feeding damage.",
        "pesticide_treatments": "Abamectin (0.5 ml/L), Spiromesifen, or Bifenazate. Spray both leaf surfaces. Rotate miticides to prevent resistance. Sulphur (2 g/L) as an organic option.",
        "soil_moisture": "Maintain adequate irrigation — drought-stressed plants are most vulnerable. Overhead misting during early infestation can help reduce mite populations.",
        "preventive_measures": "Avoid water stress, remove heavily infested leaves, introduce predatory mite Phytoseiulus persimilis in protected cultivation.",
        "additional_recommendations": "Major pest in Rajasthan and Gujarat during hot, dry periods. Check leaf undersides weekly with a hand lens. Early detection is critical — populations double every 3–5 days.",
    },
    "Tomato___Target_Spot": {
        "crop_type": "Tomato",
        "disease": "Target Spot",
        "description": "Brown spots with concentric rings (target appearance) and yellow halos on leaves and fruit. Causes defoliation and fruit lesions reducing yield and marketability.",
        "causes": "Fungus Corynespora cassiicola. Favored by warm, humid conditions (24–30 °C). Spreads by wind and rain splash from infected debris.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Balanced NPK. Potassium and calcium strengthen tissue against infection.",
        "pesticide_treatments": "Azoxystrobin + Chlorothalonil, Mancozeb, or Fluxapyroxad. Apply at 10–14 day intervals preventively.",
        "soil_moisture": "Drip irrigation; avoid wetting foliage. Mulching reduces splash dispersal.",
        "preventive_measures": "Remove infected lower leaves, maintain plant spacing, 2-year crop rotation with non-solanaceous crops.",
        "additional_recommendations": "Emerging disease in South Indian tomato crops — often misdiagnosed as early blight. Confirm with extension officer if unsure.",
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "crop_type": "Tomato",
        "disease": "Tomato Yellow Leaf Curl Virus (TYLCV)",
        "description": "Leaves curl upward and inward, turn yellow at margins, and become leathery. Infected plants are stunted with severely reduced fruit set. One of India's most devastating tomato diseases.",
        "causes": "Begomovirus transmitted by whitefly Bemisia tabaci. Virus cannot spread plant-to-plant — whitefly is the only vector. Warm, dry weather favors whitefly proliferation.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Balanced nutrition keeps plants vigorous. Do not over-fertilize nitrogen which attracts whiteflies.",
        "pesticide_treatments": "Control whitefly vector: Imidacloprid (0.3 ml/L) or Thiamethoxam as soil drench + foliar. Spirotetramat for nymph control. Rotate insecticides to prevent resistance.",
        "soil_moisture": "Consistent drip irrigation reduces plant stress and attractiveness to whitefly.",
        "preventive_measures": "Plant TYLCV-resistant varieties (Arka Rakshak, Pusa Rohini). Use yellow sticky traps (10/acre). Install insect-proof netting in nursery. Rogue out infected plants immediately.",
        "additional_recommendations": "Most damaging tomato disease in Karnataka, AP, TN, and Gujarat. Whitefly populations peak in October–December. Nursery protection with 40-mesh nets prevents primary infection.",
    },
    "Tomato___Tomato_mosaic_virus": {
        "crop_type": "Tomato",
        "disease": "Tomato Mosaic Virus (ToMV)",
        "description": "Light and dark green mosaic mottling on leaves; leaves may be distorted, narrow, or fern-like. Fruits may show yellow blotches. Causes significant yield loss.",
        "causes": "Tobamovirus (ToMV). Extremely stable — spread by mechanical contact, contaminated tools, hands, and infected seed. NOT insect-transmitted.",
        "soil_requirements": "Well-drained loam, pH 6.0–6.8.",
        "recommended_fertilizers": "Balanced NPK. Well-nourished plants tolerate virus better.",
        "pesticide_treatments": "No chemical cure for viral diseases. Control with good sanitation. Milk spray (10% skim milk) inactivates the virus on plant surfaces.",
        "soil_moisture": "Consistent irrigation to reduce plant stress.",
        "preventive_measures": "Use resistant varieties and certified virus-free seed. Wash hands with soap before handling plants. Disinfect tools with 1% sodium hypochlorite. Remove infected plants.",
        "additional_recommendations": "Spreads very rapidly in nurseries through routine operations. Avoid touching plants after handling infected material. Smoking tobacco can transmit related TMV — instruct workers not to smoke in the field.",
    },
    "Tomato___healthy": {
        "crop_type": "Tomato",
        "disease": "Healthy (No Disease Detected)",
        "description": "Tomato plant is healthy. Continue standard crop management for maximum yield.",
        "causes": "N/A",
        "soil_requirements": "Deep, well-drained loamy soil, pH 6.0–7.0, rich in organic matter.",
        "recommended_fertilizers": "NPK 150:75:75 kg/ha. Split N into 3 doses (basal, 30 DAT, 50 DAT). Calcium nitrate foliar spray prevents blossom end rot. FYM 20–25 t/ha at land prep.",
        "pesticide_treatments": "Preventive copper spray monthly. Scout weekly for whitefly, aphids, and fruit borer. Apply Bacillus thuringiensis (Bt) for caterpillar control.",
        "soil_moisture": "Consistent drip irrigation — 1.2–2.0 L/plant/day. Critical at flowering and fruit development. Avoid water stress which causes blossom drop.",
        "preventive_measures": "Stake plants by 30 DAT, prune suckers weekly, mulch with black plastic, install yellow sticky traps (10/acre).",
        "additional_recommendations": "For export-quality tomatoes in AP and Karnataka, maintain harvest schedule every 3–4 days. Use plastic crates instead of gunny bags to reduce post-harvest losses.",
    },
}
